FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_FRONTEND_IMG_URL
ARG NEXT_PUBLIC_FRONTEND_BASE_URL

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_FRONTEND_IMG_URL=$NEXT_PUBLIC_FRONTEND_IMG_URL
ENV NEXT_PUBLIC_FRONTEND_BASE_URL=$NEXT_PUBLIC_FRONTEND_BASE_URL

ENV NODE_ENV=production
RUN npm run build 

EXPOSE 3000

CMD ["npm", "start", "--", "-p", "${PORT:-3000}"] 